version: '3.4'
services:
  godotty:
    image: docker.io/golang:1.11
    working_dir: /opt/src
    environment:
      HOME: /home/fake
      GOCACHE: /go/cache
      CGO_ENABLED: "0"
    volumes:
    - .:/opt/src
    - golang_cache:/go
volumes:
  golang_cache:
