# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
        environment:
          NO_DOCKER: 1
          CGO_ENABLED: "0"
    working_directory: /go/src/github.com/TimJones/godotty
    steps:
      - checkout
      - run: make bin
  check_formatting:
    docker:
      - image: circleci/golang:1.11
        environment:
          NO_DOCKER: 1
          CGO_ENABLED: "0"
    working_directory: /go/src/github.com/TimJones/godotty
    steps:
      - checkout
      - run: make check-fmt
  unit_tests:
    docker:
      - image: circleci/golang:1.11
        environment:
          NO_DOCKER: 1
          CGO_ENABLED: "0"
    working_directory: /go/src/github.com/TimJones/godotty
    steps:
      - checkout
      - run: make test
workflows:
  version: 2
  check:
    jobs:
      - build
      - check_formatting
      - unit_tests
